require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '923024806614',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'Ā hād Méi móu dé',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'on',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkNOTFZhVWs3elhVQTBRc210Vk9kMlIvRFFPbnFSYkNoeDlpa3J1eWhVYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaERjNTBmQ3ZXc3lyV2l4cmFyYlM3cVpObkN4eWdSRjhFd3lyZ2JCR2ZTYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJxRWpwczZmTUM3cW5iWkltRmk2R25HaGkvV1kyNk15Y3RxdU1TWjh3M25zPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ3Snk2Z29IRWo3STZRSmpReW5uRDlWRTdtUUZpSFJpaGdKN2c2aElBbFhFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNFWk5rOTR2NSszMUxtcm0vaTZkWGR6UmlRRnNxQ0tqSTNSak9nVGV0bmc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBJM1JYTFQ4OWh6NWhZWWlZWS9QUGZ0RFVHUTFLcFlQT0tsNnVFZE5DQWs9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUdDdEI1RXloeExDWkZIcmlJMEZxY2U2YW5QcWd0aWE3RUVEd3JhVmRWaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOFNmMEUxd1ZRVnNuNlhyWWxSRS9hYWJFWUFtWDZZSTAwVk1ieUp2N0NDST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ino1Yyt3bnZmTkc2U2Y0cktGYmlETnFzODJpTC81c3E1ZENFYUYwMHRaUE4rWHpRUHUrbTZDYzlFcTlXWFIwelE1blgxMkUzQUQ5L0dYSEN3bExBUUNBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjE5LCJhZHZTZWNyZXRLZXkiOiJBWTkzNWRHbUVoYmZoK0QrSDZWNmxna3NUK3FYcWg5TE0wZUdlbFdDcXdjPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkyMzAyNDgwNjYxNEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQzE4NkVFNjUyRTkzREVBMkI3RDgyNzRENDFBQkUxMyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzU3MjY1NjY1fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MjMwMjQ4MDY2MTRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUM1M0Q1NDFDQ0VCRDlCRDZCMTNDMDkzM0E4OTY0QjAifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NzI2NTY2Nn0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzMDI0ODA2NjE0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDNjQ4QkIxQzI0REVDMjBEMEVCNjY1MTQ5QzFGRTU1In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTcyNjU2Nzh9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IlNNMkJHTFNUIiwibWUiOnsiaWQiOiI5MjMwMjQ4MDY2MTQ6NDlAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiI1NzM4MTI5OTk3ODQ1ODo0OUBsaWQiLCJuYW1lIjoixIAgaMSBZCBNw6lpIG3Ds3UgZMOpIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNJQ2k3cXdHRU8zOTlzVUdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiI0U3VIU29IRmltQ2ptUmJBTnBlQkJPU01aQXpuekJoOUJlWmhZMW54M2pFPSIsImFjY291bnRTaWduYXR1cmUiOiJNRHVVZVAvYkJ1WXZOekZ1WjJBeDlWaFlSUEt2ZHlXeStaQncxWTdYaHI2Y0VjYWhVUXRUcFRUckRvUnhWemdwa0dNLysvR0hKZTFJWktVTVJSU0JBUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiWVhIM3BQQU1scUsxMHB6SzNtV2x0eGlaT3JOMW1VWTF0WmlSU0FJR3pIMDllL0xTeDVoM05hTVREOVFrakZHWVZEcnFmWUg5YWFxUHYrODcyb0JvQUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5MjMwMjQ4MDY2MTQ6NDlAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZUVyaDBxQnhZcGdvNWtXd0RhWGdRVGtqR1FNNTh3WWZRWG1ZV05aOGQ0eCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FJSURRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU3MjY1NjU5LCJsYXN0UHJvcEhhc2giOiIzUjlaMzkiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUdnOSJ9',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
